_wandb:
    value:
        cli_version: 0.25.1
        e:
            5arzjc7i2nd4n7yzah4oikgh046r5xzg:
                args:
                    - --technology
                    - convnavi
                    - --chatbot
                    - http://127.0.0.1:8000/query
                    - --user
                    - examples/profiles/poi-search
                    - --personality
                    - ./personalities_car/
                    - --save_folder
                    - results/poi-search
                    - --generator_llm
                    - gpt-4o-mini
                    - --judge_llm
                    - gpt-5-mini
                    - --population_size
                    - "2"
                    - --max_time
                    - "00:01:00"
                codePath: src/sensei-chat.py
                codePathLocal: src/sensei-chat.py
                cpu_count: 4
                cpu_count_logical: 8
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "216419323904"
                        used: "194658193408"
                email: lev.sorokin@tum.de
                executable: /home/lev/Documents/testing/LLM/sensei/venv/bin/python
                git:
                    commit: 5ca476555856dfd5c0bc6201e52586d161cd384c
                    remote: git@github.com:Leviathan321/sensei.git
                gpu: NVIDIA GeForce 940MX
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Maxwell
                      cudaCores: 384
                      memoryTotal: "2147483648"
                      name: NVIDIA GeForce 940MX
                      uuid: GPU-f79d740a-3db2-59a6-0145-059591a6c27d
                host: lev-ubuntu
                memory:
                    total: "16611430400"
                os: Linux-5.15.0-139-generic-x86_64-with-glibc2.31
                program: /home/lev/Documents/testing/LLM/sensei/src/sensei-chat.py
                python: CPython 3.10.16
                root: /home/lev/Documents/testing/LLM/sensei
                startedAt: "2026-03-14T22:42:38.665158Z"
                writerId: 5arzjc7i2nd4n7yzah4oikgh046r5xzg
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 5
                - 49
                - 53
                - 95
                - 105
            "2":
                - 5
                - 49
                - 53
                - 95
                - 105
            "3":
                - 2
                - 13
                - 15
                - 16
                - 61
                - 62
            "4": 3.10.16
            "5": 0.25.1
            "12": 0.25.1
            "13": linux-x86_64
algorithm:
    value: sensei
chatbot:
    value: http://127.0.0.1:8000/query
critical_threshold:
    value: 0.7
generator_llm:
    value: gpt-4o-mini
judge_llm:
    value: gpt-5-mini
max_time:
    value: "00:01:00"
no_wandb:
    value: false
personality:
    value: ./personalities_car/
personality_file:
    value: personalities_car/conversational-user.yml
personality_name:
    value: conversational-user
population_size:
    value: 2
save_folder:
    value: results/poi-search
seed:
    value: 1
shuffle_personalities:
    value: false
sut:
    value: IPA_YELP
technology:
    value: convnavi
user:
    value: examples/profiles/poi-search
wandb_entity:
    value: mt-test
wandb_group:
    value: null
wandb_project:
    value: NaviYelp
weight_clarity:
    value: 0.5
weight_request_orientedness:
    value: 0.5
